language: php
php:
  - 5.5
  - 5.6
install:
  - composer self-update
  - composer update --dev
addons:
  code_climate:
    repo_token: dcb2b82099fe51223576942db0744a4c3eb21ac2886eba91088edb2a70993f3b
after_script:
  - vendor/bin/test-reporter